[package]
name = "ecobee"
version = "0.1.0"
authors = ["Trevor Berninger <trevor@lightfieldlab.com>"]
edition = "2018"

[dependencies]
ureq = "2.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
